services:
  integraaal-frontend:
    image: integraaal-frontend:latest
    container_name: frontend
    restart: always
    networks:
      - traefik-public
      - default
    pull_policy: "never"
    build:
      context: "./"
    ports:
      - "8044:8044"

    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public

      - traefik.http.services.${STACK_NAME?Variable not set}-frontend.loadbalancer.server.port=8044

      - traefik.http.routers.${STACK_NAME?Variable not set}-frontend-http.rule=Host(`${DOMAIN?Variable not set}`)
      - traefik.http.routers.${STACK_NAME?Variable not set}-frontend-http.entrypoints=http


networks:
  traefik-public:
    external: true
  default:
    driver: bridge


