user nginx;
worker_processes 1;

pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    access_log /dev/stdout;
    error_log /dev/stderr;

    sendfile on;
    keepalive_timeout 30;
    gzip on;

    server {
        listen      8044;
        root        /app/dist;

        location / {
            try_files $uri /index.html$is_args$args;
        }
    }

}

