/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/layout/AppBar.vue')['default']
    AppDrawer: typeof import('./components/layout/AppDrawer.vue')['default']
    AppDrawerItem: typeof import('./components/layout/AppDrawerItem.vue')['default']
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppNotification: typeof import('./components/layout/AppNotification.vue')['default']
    AppNotificationItem: typeof import('./components/layout/AppNotificationItem.vue')['default']
    ApproveChain: typeof import('./components/das/ApproveChain.vue')['default']
    Button: typeof import('./components/ui/Button.vue')['default']
    ButtonSettings: typeof import('./components/layout/ButtonSettings.vue')['default']
    Combobox: typeof import('./components/ui/Combobox.vue')['default']
    CreateRequest: typeof import('./components/das/CreateRequest.vue')['default']
    CreationDialog: typeof import('./components/link/CreationDialog.vue')['default']
    DocumentDialog: typeof import('./components/partner/DocumentDialog.vue')['default']
    Edit: typeof import('./components/product/Edit.vue')['default']
    FeedbacksList: typeof import('./components/support/FeedbacksList.vue')['default']
    Header: typeof import('./components/product/Header.vue')['default']
    HistoryDialog: typeof import('./components/product/HistoryDialog.vue')['default']
    Input: typeof import('./components/ui/Input.vue')['default']
    Ozon: typeof import('./components/product/Ozon.vue')['default']
    Pim: typeof import('./components/product/Pim.vue')['default']
    QuestionsList: typeof import('./components/support/QuestionsList.vue')['default']
    Request: typeof import('./components/das/Request.vue')['default']
    RouterWrapper: typeof import('./components/layout/RouterWrapper.vue')['default']
    Search: typeof import('./components/Search.vue')['default']
    SearchInput: typeof import('./components/SearchInput.vue')['default']
    Select: typeof import('./components/ui/Select.vue')['default']
    UnionDialog: typeof import('./components/product/UnionDialog.vue')['default']
    UploadMedia: typeof import('./components/product/upload/UploadMedia.vue')['default']
    Wb: typeof import('./components/product/Wb.vue')['default']
  }
}
