/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/backoffice': RouteRecordInfo<'/backoffice', '/backoffice', Record<never, never>, Record<never, never>>,
    '/bloggers': RouteRecordInfo<'/bloggers', '/bloggers', Record<never, never>, Record<never, never>>,
    '/catalogs/product/[id]': RouteRecordInfo<'/catalogs/product/[id]', '/catalogs/product/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/catalogs/product/new': RouteRecordInfo<'/catalogs/product/new', '/catalogs/product/new', Record<never, never>, Record<never, never>>,
    '/catalogs/products': RouteRecordInfo<'/catalogs/products', '/catalogs/products', Record<never, never>, Record<never, never>>,
    '/cms': RouteRecordInfo<'/cms', '/cms', Record<never, never>, Record<never, never>>,
    '/cms/bloggers/': RouteRecordInfo<'/cms/bloggers/', '/cms/bloggers', Record<never, never>, Record<never, never>>,
    '/cms/bloggers/[id]': RouteRecordInfo<'/cms/bloggers/[id]', '/cms/bloggers/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/cms/bloggers/[id].edit': RouteRecordInfo<'/cms/bloggers/[id].edit', '/cms/bloggers/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/cms/bloggers/new': RouteRecordInfo<'/cms/bloggers/new', '/cms/bloggers/new', Record<never, never>, Record<never, never>>,
    '/cms/budget': RouteRecordInfo<'/cms/budget', '/cms/budget', Record<never, never>, Record<never, never>>,
    '/cms/overlimit': RouteRecordInfo<'/cms/overlimit', '/cms/overlimit', Record<never, never>, Record<never, never>>,
    '/cms/publications': RouteRecordInfo<'/cms/publications', '/cms/publications', Record<never, never>, Record<never, never>>,
    '/das': RouteRecordInfo<'/das', '/das', Record<never, never>, Record<never, never>>,
    '/das/request/[id]': RouteRecordInfo<'/das/request/[id]', '/das/request/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/das/request/edit/[id]': RouteRecordInfo<'/das/request/edit/[id]', '/das/request/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/das/request/new': RouteRecordInfo<'/das/request/new', '/das/request/new', Record<never, never>, Record<never, never>>,
    '/das/requests': RouteRecordInfo<'/das/requests', '/das/requests', Record<never, never>, Record<never, never>>,
    '/das/search': RouteRecordInfo<'/das/search', '/das/search', Record<never, never>, Record<never, never>>,
    '/design': RouteRecordInfo<'/design', '/design', Record<never, never>, Record<never, never>>,
    '/dms/link/[id]': RouteRecordInfo<'/dms/link/[id]', '/dms/link/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dms/links': RouteRecordInfo<'/dms/links', '/dms/links', Record<never, never>, Record<never, never>>,
    '/dms/offer/[id]': RouteRecordInfo<'/dms/offer/[id]', '/dms/offer/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dms/offers': RouteRecordInfo<'/dms/offers', '/dms/offers', Record<never, never>, Record<never, never>>,
    '/dms/partnerDoc/[id]': RouteRecordInfo<'/dms/partnerDoc/[id]', '/dms/partnerDoc/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dms/partnerManager/[id]': RouteRecordInfo<'/dms/partnerManager/[id]', '/dms/partnerManager/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dms/partnersDoc': RouteRecordInfo<'/dms/partnersDoc', '/dms/partnersDoc', Record<never, never>, Record<never, never>>,
    '/dms/partnersManager': RouteRecordInfo<'/dms/partnersManager', '/dms/partnersManager', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/partners': RouteRecordInfo<'/partners', '/partners', Record<never, never>, Record<never, never>>,
    '/special-projects': RouteRecordInfo<'/special-projects', '/special-projects', Record<never, never>, Record<never, never>>,
    '/special-projects/dbf': RouteRecordInfo<'/special-projects/dbf', '/special-projects/dbf', Record<never, never>, Record<never, never>>,
    '/special-projects/leftovers': RouteRecordInfo<'/special-projects/leftovers', '/special-projects/leftovers', Record<never, never>, Record<never, never>>,
    '/special-projects/operations': RouteRecordInfo<'/special-projects/operations', '/special-projects/operations', Record<never, never>, Record<never, never>>,
    '/support': RouteRecordInfo<'/support', '/support', Record<never, never>, Record<never, never>>,
    '/support/supportChat': RouteRecordInfo<'/support/supportChat', '/support/supportChat', Record<never, never>, Record<never, never>>,
    '/support/supportWb': RouteRecordInfo<'/support/supportWb', '/support/supportWb', Record<never, never>, Record<never, never>>,
    '/xlsx': RouteRecordInfo<'/xlsx', '/xlsx', Record<never, never>, Record<never, never>>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
